# screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# player
PLAYER_RADIUS = 20
LINE_WIDTH = 2

# powerups
POWERUP_SPAWN_TIMER = 1
POWERUP_KINDS = 3
POWERUP_LINE_WIDTH = 2
SHIELD_LINE_WIDTH = 3

# shooting
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# moving and turning
PLAYER_TRUN_SPEED = 300
PLAYER_SPEED = 200

# asteroids radius, kinds, spawn rate and max radius
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS